---
# ANSIBLE PLAYBOOK
# para transferir os ficheiros jar para as machines da sala de aula
# 
# Requer o ansible instalado na máquina "source", python instalado na máquina destino
# 
# STEPS:
# - Copiar o conteudo do ficheiro hosts para /etc/ansible/hosts 
#   (para não interferir com outros hosts caso tenhas)
#   lá estão os dados para se aceder a todas as maquinas, incluíndo username e password
#   (não recomendado)
# 
# - Gerar ficheiros jar no IntelliJ para todos os projetos
#   (File > Project Structure > Artifacts > + > JAR > From modules.. > 
#   Escolher Main Class (clicando na pasta) > Extract to the target JAR > OK)
#   Depois, (Build > Build Artifacts > Build)
# 
# - Alterar este ficheiro com o caminho completo para os jars que foram criados
# 
# - Ligar à VPN da UA (caso não estejas na rede da UA)
# 
# - Executar "ansible-playbook playbook.yml -v"
#   (caso hajam erros com o -v dá para mostrar mais qualquer coisa)
# 

# REPOSITORY

- name: Setting up Repository machine
  hosts: repository

  tasks:
  - name: Create repository directory 
    command: mkdir -p repository

  - name: Copy repository jar file to repository machine
    copy: 
      src: "{{ playbook_dir }}/generalrepository_machine/repository.jar"
      dest: ./repository/

# LOUNGE

- name: Setting up Lounge machine
  hosts: lounge

  tasks:
  - name: Create lounge directory 
    command: mkdir -p lounge

  - name: Copy lounge jar file to lounge machine
    copy: 
      src: "{{ playbook_dir }}/lounge_machine/lounge.jar"
      dest: ./lounge/

# OUTSIDE WORLD

- name: Setting up OutsideWorld machine
  hosts: outsideworld

  tasks:
  - name: Create OutsideWorld directory 
    command: mkdir -p outsideworld

  - name: Copy OutsideWorld jar file to OutsideWorld machine
    copy: 
      src: "{{ playbook_dir }}/outsideworld_machine/outsideworld.jar"
      dest: ./outsideworld/

# PARK

- name: Setting up Park machine
  hosts: park

  tasks:
  - name: Create Park directory 
    command: mkdir -p park

  - name: Copy Park jar file to Park machine
    copy: 
      src: "{{playbook_dir}}/park_machine/park.jar"
      dest: ./park/

# SUPPLIER SITE

- name: Setting up SupplierSite machine
  hosts: suppliersite

  tasks:
  - name: Create SupplierSite directory 
    command: mkdir -p suppliersite

  - name: Copy SupplierSite jar file to SupplierSite machine
    copy: 
      src: "{{playbook_dir}}/suppliersite_machine/suppliersite.jar"
      dest: ./suppliersite/

# REPAIR AREA

- name: Setting up RepairArea machine
  hosts: repairarea

  tasks:
  - name: Create RepairArea directory 
    command: mkdir -p repairarea

  - name: Copy repairarea jar file to repairarea machine
    copy: 
      src: "{{playbook_dir}}/repairarea_machine/repairarea.jar"
      dest: ./repairarea/

# CUSTOMER

- name: Setting up Customer machine
  hosts: customer

  tasks:
  - name: Create customer directory 
    command: mkdir -p customer

  - name: Copy customer jar file to customer machine
    copy: 
      src: "{{playbook_dir}}/customer_machine/customer.jar"
      dest: ./customer/

# MECHANIC

- name: Setting up mechanic machine
  hosts: mechanic

  tasks:
  - name: Create mechanic directory 
    command: mkdir -p mechanic

  - name: Copy mechanic jar file to mechanic machine
    copy: 
      src: "{{playbook_dir}}/mechanic_machine/mechanic.jar"
      dest: ./mechanic/

# MANAGER

- name: Setting up manager machine
  hosts: manager

  tasks:
  - name: Create manager directory 
    command: mkdir -p manager

  - name: Copy manager jar file to manager machine
    copy: 
      src: "{{playbook_dir}}/manager_machine/manager.jar"
      dest: ./manager/
